
undefined * FUN_080040d8(undefined *param_1);
undefined8 FUN_080040fc(undefined *param_1,undefined *param_2);
ulonglong FUN_08004118(uint param_1,uint param_2,uint param_3,uint param_4);
ulonglong FUN_0800411e(uint param_1,uint param_2,uint param_3,uint param_4);
uint32_t SX126xConvertFreqInHzToPllStep(uint32_t freqInHz);
ulonglong FUN_08004490(uint param_1,uint param_2,uint param_3,uint param_4);
ulonglong FUN_0800466c(uint param_1,uint param_2,uint param_3,uint param_4);
ulonglong FUN_080046e4(uint param_1,uint param_2,uint param_3,uint param_4);
ulonglong FUN_08004852(uint param_1,uint param_2,uint param_3,uint param_4);
int32_t FUN_080048b4(uint param_1,uint param_2);
void SystemInit(void);
void Reset_Handler(void);
void Default_Handler(void);
void delay_us(int param_1);
int32_t flash_erase_page(uint32_t addr);
int32_t flash_program_bytes(uint32_t addr,uint8_t *data,uint32_t size);
void gpio_init(gpio_t *gpiox,uint8_t gpio_pin,gpio_mode_t mode);
uint8_t gpio_read(gpio_t *gpiox,uint8_t gpio_pin);
void gpio_toggle(gpio_t *gpiox,uint8_t gpio_pin);
void gpio_set_iomux(gpio_t *gpiox,uint8_t gpio_pin,uint8_t func_num);
void check_iwdg_sr_done(void);
void iwdg_init(bool auto_reset);
void iwdg_set_prescaler(undefined prescaler);
void iwdg_set_reload(uint32_t value);
void FUN_08004cd8(void);
void iwdg_start(void);
void iwdg_stop(void);
void lptimer_init(lptimer_t *LPTIMERx,lptimer_init_t init);
void lptimer_cmd(lptimer_t *LPTIMERx,bool state);
void lptimer_config_count_mode(lptimer_t *LPTIMERx,lptimer_mode_t count_mode,uint8_t state);
void lptimer_config_interrupt(lptimer_t *LPTIMERx,lptimer_it_t interrupt,uint8_t state);
void lptimer_clear_interrupt(lptimer_t *LPTIMERx,lptimer_it_t interrupt);
void lptimer_set_arr_register(lptimer_t *LPTIMERx,uint16_t arr_value);
void lptimer_set_cmp_register(lptimer_t *LPTIMERx,uint16_t cmp_value);
bool lptimer_get_clear_status_flag(lptimer_t *LPTIMERx,uint status_flag);
bool lptimer_get_status(lptimer_t *LPTIMERx,lptimer_status_t status);
uint32_t rcc_get_clk_freq(rcc_clk_t clk);
void rcc_set_lptimer0_clk_source(rcc_lptimer0_clk_source_t clk_source);
void rcc_set_iwdg_clk_source(uint8_t clk_source);
uint rcc_get_uart0_clk_source(void);
uint rcc_get_uart1_clk_source(void);
uint rcc_get_uart2_clk_source(void);
uint rcc_get_uart3_clk_source(void);
void rcc_enable_peripheral_clk(rcc_peripheral_t peripheral,bool new_state);
void rcc_enable_oscillator(rcc_oscillator_t osc,bool new_state);
void rcc_rst_peripheral(rcc_peripheral_t peripheral,bool new_state);
bool uart_get_flag_status(uart_t *uartx,uint32_t uart_flag);
void uart_config_interrupt(UART1 *uartx,uint32_t uart_interrupt,bool new_state);
void uart_config_init(uart_config_t *config);
void uart_cmd(uart_t *uartx,bool new_state);
bool uart_get_interrupt_status(UART1 *uartx,uint32_t uart_interrupt);
int32_t uart_init(uart_t *uartx,uart_config_t *config);
uint FUN_080056d4(void);
undefined8 FUN_0800572c(int param_1,uint param_2);
void FUN_08005788(void);
void LPTIM0_Handler(void);
uint16_t crc16(uint16_t crc,uint8_t data);
void FUN_08005a60(int param_1,uint *param_2,int *param_3);
void Radio_Init(int param_1);
void FUN_08005bf4(void);
uint FUN_08005c28(uint param_1);
void main(void);
void FUN_0800694c(void);
void FUN_08006950(void);
void FUN_08006990(uint param_1);
void uarts_init(uint8_t protocol);
void UART0_Handler(void);
bool FUN_08006c10(uint param_1);
undefined4 FUN_08006ca0(ushort *param_1);
undefined4 FUN_08006db0(void);
undefined4 FUN_08006e14(void);
void UART1_Handler(void);
undefined2 FUN_08006f04(uint param_1);
void FUN_08006f9c(uint param_1);
void uart_setbuffer(uint32_t params,uint8_t *buf,uint16_t buf_size);
void FUN_08006fbc(uint param_1);
undefined4 FUN_08006fd4(ushort *param_1);
void NMI_Handler(void);
void HardFault_Handler(void);
void MemManage_Handler(void);
void BusFault_Handler(void);
void UsageFault_Handler(void);
void SVC_Handler(void);
void PendSV_Handler(void);
void SysTick_Handler(void);
void PWR_Handler(void);
void FUN_0800713a(int param_1,undefined4 param_2,undefined4 param_3);
int FUN_08007144(int *param_1,int param_2);
void SX126xCheckDeviceReady(void);
void SX126xSetCrcSeed(uint16_t seed);
void SX126xSetCrcPolynomial(uint16_t polynomial);
void SX126xSetStandby(RadioStandbyModes_t mode);
void SX126xSetRxBoosted(uint32_t timeout);
void SX126xSetStopRxTimerOnPreambleDetect(bool enable);
void SX126xSetLoRaSymbNumTimeout(uint8_t symbNum);
void SX126xSetRegulatorMode(uint8_t mode);
void SX126xCalibrate(uint8_t calibParam);
void SX126xCalibrateImage(uint32_t f1,uint32_t f2);
void SX126xSetPaConfig(uint8_t paDutyCycle,uint8_t hpMax,uint8_t deviceSel,uint8_t paLut);
void SX126xSetRxTxFallbackMode(uint8_t fallbackMode);
void SX126xSetDioIrqParams(uint16_t irqMask,uint16_t dio1Mask,uint16_t dio2Mask,uint16_t dio3Mask);
void SX126xInit(void);
void SX126xSetRfFrequency(uint32_t frequency);
void SX126xSetPacketType(uint8_t packetType);
void SX126xSetTxParams(int8_t power,RadioRampTimes_t rampTime);
void SX126xSetModulationParams(ModulationParams_t *modulationParams);
void SX126xSetPacketParams(char *packetParams);
void SX126xSetBufferBaseAddress(uint8_t txBaseAddress,uint8_t rxBaseAddress);
void SX126xGetRxBufferStatus(uint8_t *payloadLength,uint8_t *rxStartBufferPointer);
uint8_t SX126xGetPayload(uint8_t *buffer,uint8_t *size,uint8_t maxSize);
void SX126xGetPacketStatus(PacketStatus_t *pktStatus);
void LORAC_Handler(void);
uint16_t SpiInOut(uint16_t outData);
void SX126xLoracInit(void);
void SX126xReset(void);
void SX126xWaitOnBusy(void);
void SX126xWakeup(void);
uint SX126xWriteCommand(uint16_t command,uint8_t *buffer,uint16_t size);
void SX126xReadCommand(undefined4 command,uint8_t *buffer,uint16_t size);
void SX126xWriteRegisters(uint16_t address,uint8_t *buffer,uint16_t size);
void SX126xWriteRegister(uint16_t address,uint8_t value);
void SX126xReadRegisters(uint16_t address,uint8_t *buffer,uint16_t size);
uint8_t SX126xReadRegister(uint16_t address);
void SX126xReadBuffer(uint8_t offset,uint8_t *buffer,uint8_t size);
void SX126xSetRfTxPower(int8_t power);
uint8_t SX126xGetPaSelect(uint32_t channel);
void SX126xAntSwOn(void);
void FUN_08007a4c(void);
void memset(uint8_t *dest,uint8_t data,uint32_t size);
int32_t FUN_08007b34(int32_t param_1);
void FUN_08007b74(void);
void FUN_08007b80(void);

